# fly.toml app configuration file generated for clone-twiiter on 2023-05-14T09:45:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clone-twitter-2078"
primary_region = "mia"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
